### ISSUE TITLE
A couple of HTML Validation errors - 72 hour additional time window provided

### ISSUE THREAD

**Issue by neilmispelaar** [imd1005-web-development-winter-2023/assignment-02-Viaviaviaviaviavia#3]
Hi @Viaviaviaviaviavia 

First off, thank you for your awesome Assignment 02 submission! Love the look and feel of your web page. 

There are a few small HTML issues that were thrown when I ran your code through the HTML Validator. Note that your CSS didn't throw an error so yay 🎉.

**If you would like to take some additional time to address these small items, or make any further tweaks to your page, you may make changes to your code for the the next 72 hours without penalty.**

Here are a few of the HTML validation errors that were thrown:

<img width="1468" alt="Screenshot 2023-02-20 at 9 44 33 AM" src="https://user-images.githubusercontent.com/9325038/220137194-a82ce897-cc96-49d7-9de9-5c7367df9f7f.png">

For the full list of items: 

https://validator.w3.org/nu/?doc=https%3A%2F%2Fimd1005-web-development-winter-2023.github.io%2Fassignment-02-Viaviaviaviaviavia%2F

I also ran your code through the CSS Validator and there were no errors! So congratulations on that.

CSS Validator link:

https://jigsaw.w3.org/css-validator/validator?uri=https%3A%2F%2Fimd1005-web-development-winter-2023.github.io%2Fassignment-02-Viaviaviaviaviavia%2F&profile=css3svg&usermedium=all&warning=1&vextwarning=&lang=en

**Comment by ViaTheCode** [comment]
Thank you so much, I really appreciate it!
I didn't realize having spaces in the image names would cause problems, and thank you again for giving me the opportunity to fix it!

Sent from Outlook for Android<https://aka.ms/AAb9ysg>

________________________________
From: Neil Mispelaar ***@***.***>
Sent: Monday, 20 February 2023, 9:46 am
To: imd1005-web-development-winter-2023/assignment-02-Viaviaviaviaviavia ***@***.***>
Cc: Violet Amey-Quade ***@***.***>; Mention ***@***.***>
Subject: [imd1005-web-development-winter-2023/assignment-02-Viaviaviaviaviavia] A couple of HTML Validation errors - 72 hour additional time window provided (Issue #3)

[External Email]

Hi @Viaviaviaviaviavia<https://can01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FViaviaviaviaviavia&data=05%7C01%7Cvioletameyquade%40cmail.carleton.ca%7C6fec08ec15424c5eabe908db13513762%7C6ad91895de06485ebc51fce126cc8530%7C0%7C0%7C638125011761051875%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=CaKZ3pLmRxV1TXuIIDkCcRNjEtYjOH8cQkw%2FnPDnEVk%3D&reserved=0>

First off, thank you for your awesome Assignment 02 submission! Love the look and feel of your web page.

There are a few small HTML issues that were thrown when I ran your code through the HTML Validator. Note that your CSS didn't throw an error so yay 🎉.

If you would like to take some additional time to address these small items, or make any further tweaks to your page, you may make changes to your code for the the next 72 hours without penalty.

Here are a few of the HTML validation errors that were thrown:

[Screenshot 2023-02-20 at 9 44 33 AM]<https://can01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F9325038%2F220137194-a82ce897-cc96-49d7-9de9-5c7367df9f7f.png&data=05%7C01%7Cvioletameyquade%40cmail.carleton.ca%7C6fec08ec15424c5eabe908db13513762%7C6ad91895de06485ebc51fce126cc8530%7C0%7C0%7C638125011761051875%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=LFSmnQG9hcTV1R3tQil8bf1dau8t8L6l1g53v%2F0kI2E%3D&reserved=0>

For the full list of items:

https://validator.w3.org/nu/?doc=https%3A%2F%2Fimd1005-web-development-winter-2023.github.io%2Fassignment-02-Viaviaviaviaviavia%2F<https://can01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fvalidator.w3.org%2Fnu%2F%3Fdoc%3Dhttps%253A%252F%252Fimd1005-web-development-winter-2023.github.io%252Fassignment-02-Viaviaviaviaviavia%252F&data=05%7C01%7Cvioletameyquade%40cmail.carleton.ca%7C6fec08ec15424c5eabe908db13513762%7C6ad91895de06485ebc51fce126cc8530%7C0%7C0%7C638125011761051875%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=Klwhdu72K56y7AvnjHAgBmsw59rFf13XzAvhnXyl%2BpQ%3D&reserved=0>

I also ran your code through the CSS Validator and there were no errors! So congratulations on that.

CSS Validator link:

https://jigsaw.w3.org/css-validator/validator?uri=https%3A%2F%2Fimd1005-web-development-winter-2023.github.io%2Fassignment-02-Viaviaviaviaviavia%2F&profile=css3svg&usermedium=all&warning=1&vextwarning=&lang=en<https://can01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fjigsaw.w3.org%2Fcss-validator%2Fvalidator%3Furi%3Dhttps%253A%252F%252Fimd1005-web-development-winter-2023.github.io%252Fassignment-02-Viaviaviaviaviavia%252F%26profile%3Dcss3svg%26usermedium%3Dall%26warning%3D1%26vextwarning%3D%26lang%3Den&data=05%7C01%7Cvioletameyquade%40cmail.carleton.ca%7C6fec08ec15424c5eabe908db13513762%7C6ad91895de06485ebc51fce126cc8530%7C0%7C0%7C638125011761051875%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=WsHF4rafl3nDOuocSaHRzgFkns%2BXit0SKRs0N1P%2B%2FU8%3D&reserved=0>

—
Reply to this email directly, view it on GitHub<https://can01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fimd1005-web-development-winter-2023%2Fassignment-02-Viaviaviaviaviavia%2Fissues%2F3&data=05%7C01%7Cvioletameyquade%40cmail.carleton.ca%7C6fec08ec15424c5eabe908db13513762%7C6ad91895de06485ebc51fce126cc8530%7C0%7C0%7C638125011761051875%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=Z2WgnQSEaYDx4D1RDoYPHjdwI30PC%2F3p7oqUwLgTzzE%3D&reserved=0>, or unsubscribe<https://can01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FA56KLTFKSW2WVTMHQF6NUSTWYN7TNANCNFSM6AAAAAAVB64MCY&data=05%7C01%7Cvioletameyquade%40cmail.carleton.ca%7C6fec08ec15424c5eabe908db13513762%7C6ad91895de06485ebc51fce126cc8530%7C0%7C0%7C638125011761051875%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=WY6m4WKUiBVi4skhOG60QbsCBc1grIGs1tCijx6MExo%3D&reserved=0>.
You are receiving this because you were mentioned.Message ID: ***@***.***>

This email contains links to content or websites. Always be cautious when opening external links or attachments.

Please visit https://carleton.ca/its/help-centre/report-phishing/ for information on reporting phishing messages.

When in doubt, the ITS Service Desk can provide assistance. https://carleton.ca/its/chat

-----End of Disclaimer-----
